"""unique isbn

Revision ID: 01bcee71cbf7
Revises: 67b24878abb8
Create Date: 2025-05-23 13:57:57.265221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01bcee71cbf7"
down_revision: Union[str, None] = "67b24878abb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "books", ["isbn"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="unique")
    # ### end Alembic commands ###
