"""borrowed_books nullable return_at

Revision ID: 49a7e09f56f2
Revises: 01bcee71cbf7
Create Date: 2025-05-26 01:31:34.789013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49a7e09f56f2"
down_revision: Union[str, None] = "01bcee71cbf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books", "return_at", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books", "return_at", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###
